# Generated by Django 4.2.19 on 2025-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintence_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_reg_no', models.CharField(max_length=10)),
                ('maintenance_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('maintenance_date', models.DateTimeField()),
                ('next_due_date', models.DateTimeField()),
            ],
        ),
    ]
