# Generated by Django 4.2.19 on 2025-03-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_maintenance_status_maintenance_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
